/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject.finalproject;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author qazwsx922
 */
public class Food extends javax.swing.JFrame {

    /**
     * Creates new form Food
     */
    public Food() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCheckBoxFries = new javax.swing.JCheckBox();
        jCheckBoxBurger = new javax.swing.JCheckBox();
        jCheckBoxChicken = new javax.swing.JCheckBox();
        jCheckBoxSalad = new javax.swing.JCheckBox();
        jCheckBoxSandwich = new javax.swing.JCheckBox();
        jCheckBoxOnion = new javax.swing.JCheckBox();
        jCheckBoxSoup = new javax.swing.JCheckBox();
        jFormattedTextFieldSalad = new javax.swing.JFormattedTextField();
        jFormattedTextFieldFries = new javax.swing.JFormattedTextField();
        jFormattedTextFieldChicken = new javax.swing.JFormattedTextField();
        jFormattedTextFieldSandwich = new javax.swing.JFormattedTextField();
        jFormattedTextFieldSoup = new javax.swing.JFormattedTextField();
        jFormattedTextFieldOnion = new javax.swing.JFormattedTextField();
        jFormattedTextFieldBurger = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jCheckBoxIceCream = new javax.swing.JCheckBox();
        jCheckBoxPancakes = new javax.swing.JCheckBox();
        jCheckBoxMuffin = new javax.swing.JCheckBox();
        jFormattedTextFieldIceCream = new javax.swing.JFormattedTextField();
        jFormattedTextFieldPancakes = new javax.swing.JFormattedTextField();
        jFormattedTextFieldMuffin = new javax.swing.JFormattedTextField();
        jCheckBoxTea = new javax.swing.JCheckBox();
        jCheckBoxCoffee = new javax.swing.JCheckBox();
        jCheckBoxSoda = new javax.swing.JCheckBox();
        jFormattedTextFieldSoda = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCoffee = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTea = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 4));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel4.setText("MENU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 320, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 4));

        jCheckBoxFries.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBoxFries.setText("Fries");
        jCheckBoxFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFriesActionPerformed(evt);
            }
        });

        jCheckBoxBurger.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBoxBurger.setText("Burger");
        jCheckBoxBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBurgerActionPerformed(evt);
            }
        });

        jCheckBoxChicken.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBoxChicken.setText("Chicken");
        jCheckBoxChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxChickenActionPerformed(evt);
            }
        });

        jCheckBoxSalad.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBoxSalad.setText("Salad");
        jCheckBoxSalad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSaladActionPerformed(evt);
            }
        });

        jCheckBoxSandwich.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBoxSandwich.setText("Sandwich");
        jCheckBoxSandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSandwichActionPerformed(evt);
            }
        });

        jCheckBoxOnion.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBoxOnion.setText("Onion Rings");
        jCheckBoxOnion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxOnionActionPerformed(evt);
            }
        });

        jCheckBoxSoup.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBoxSoup.setText("Soup");
        jCheckBoxSoup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSoupActionPerformed(evt);
            }
        });

        jFormattedTextFieldSalad.setEnabled(false);
        jFormattedTextFieldSalad.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jFormattedTextFieldSalad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldSaladKeyTyped(evt);
            }
        });

        jFormattedTextFieldFries.setEnabled(false);
        jFormattedTextFieldFries.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jFormattedTextFieldFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldFriesActionPerformed(evt);
            }
        });
        jFormattedTextFieldFries.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldFriesKeyTyped(evt);
            }
        });

        jFormattedTextFieldChicken.setEnabled(false);
        jFormattedTextFieldChicken.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jFormattedTextFieldChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldChickenActionPerformed(evt);
            }
        });
        jFormattedTextFieldChicken.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldChickenKeyTyped(evt);
            }
        });

        jFormattedTextFieldSandwich.setEnabled(false);
        jFormattedTextFieldSandwich.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jFormattedTextFieldSandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldSandwichActionPerformed(evt);
            }
        });
        jFormattedTextFieldSandwich.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldSandwichKeyTyped(evt);
            }
        });

        jFormattedTextFieldSoup.setEnabled(false);
        jFormattedTextFieldSoup.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jFormattedTextFieldSoup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldSoupActionPerformed(evt);
            }
        });
        jFormattedTextFieldSoup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldSoupKeyTyped(evt);
            }
        });

        jFormattedTextFieldOnion.setEnabled(false);
        jFormattedTextFieldOnion.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jFormattedTextFieldOnion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldOnionActionPerformed(evt);
            }
        });
        jFormattedTextFieldOnion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldOnionKeyTyped(evt);
            }
        });

        jFormattedTextFieldBurger.setEnabled(false);
        jFormattedTextFieldBurger.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jFormattedTextFieldBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldBurgerActionPerformed(evt);
            }
        });
        jFormattedTextFieldBurger.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldBurgerKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Food");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxSoup)
                            .addComponent(jCheckBoxBurger)
                            .addComponent(jCheckBoxOnion)
                            .addComponent(jCheckBoxSandwich)
                            .addComponent(jCheckBoxSalad)
                            .addComponent(jCheckBoxChicken))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldSoup, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldOnion, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jFormattedTextFieldChicken, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jFormattedTextFieldSalad, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCheckBoxFries)
                                .addGap(70, 70, 70)
                                .addComponent(jFormattedTextFieldFries, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxBurger)
                    .addComponent(jFormattedTextFieldBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jCheckBoxFries)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxSalad))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jFormattedTextFieldFries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldSalad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxChicken)
                    .addComponent(jFormattedTextFieldChicken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxSandwich)
                    .addComponent(jFormattedTextFieldSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxOnion)
                    .addComponent(jFormattedTextFieldOnion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxSoup)
                    .addComponent(jFormattedTextFieldSoup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 320, 350));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 4));

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 180, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 4));

        jCheckBoxIceCream.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBoxIceCream.setText("Ice Cream");
        jCheckBoxIceCream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxIceCreamActionPerformed(evt);
            }
        });

        jCheckBoxPancakes.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBoxPancakes.setText("Pancakes");
        jCheckBoxPancakes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPancakesActionPerformed(evt);
            }
        });

        jCheckBoxMuffin.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBoxMuffin.setText("Muffin");
        jCheckBoxMuffin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMuffinActionPerformed(evt);
            }
        });

        jFormattedTextFieldIceCream.setEnabled(false);
        jFormattedTextFieldIceCream.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jFormattedTextFieldIceCream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldIceCreamActionPerformed(evt);
            }
        });
        jFormattedTextFieldIceCream.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldIceCreamKeyTyped(evt);
            }
        });

        jFormattedTextFieldPancakes.setEnabled(false);
        jFormattedTextFieldPancakes.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jFormattedTextFieldPancakes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldPancakesActionPerformed(evt);
            }
        });
        jFormattedTextFieldPancakes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldPancakesKeyTyped(evt);
            }
        });

        jFormattedTextFieldMuffin.setEnabled(false);
        jFormattedTextFieldMuffin.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jFormattedTextFieldMuffin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldMuffinActionPerformed(evt);
            }
        });
        jFormattedTextFieldMuffin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldMuffinKeyTyped(evt);
            }
        });

        jCheckBoxTea.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBoxTea.setText("Tea");
        jCheckBoxTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTeaActionPerformed(evt);
            }
        });

        jCheckBoxCoffee.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBoxCoffee.setText("Coffee");
        jCheckBoxCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCoffeeActionPerformed(evt);
            }
        });

        jCheckBoxSoda.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBoxSoda.setText("Soda");
        jCheckBoxSoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSodaActionPerformed(evt);
            }
        });

        jFormattedTextFieldSoda.setEnabled(false);
        jFormattedTextFieldSoda.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jFormattedTextFieldSoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldSodaActionPerformed(evt);
            }
        });
        jFormattedTextFieldSoda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldSodaKeyTyped(evt);
            }
        });

        jFormattedTextFieldCoffee.setEnabled(false);
        jFormattedTextFieldCoffee.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jFormattedTextFieldCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCoffeeActionPerformed(evt);
            }
        });
        jFormattedTextFieldCoffee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldCoffeeKeyTyped(evt);
            }
        });

        jFormattedTextFieldTea.setEnabled(false);
        jFormattedTextFieldTea.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jFormattedTextFieldTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldTeaActionPerformed(evt);
            }
        });
        jFormattedTextFieldTea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldTeaKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Desserts");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("Drinks");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBoxIceCream)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFormattedTextFieldIceCream, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBoxMuffin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFormattedTextFieldMuffin, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxSoda)
                            .addComponent(jCheckBoxCoffee)
                            .addComponent(jCheckBoxTea))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldSoda, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldTea, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCheckBoxPancakes)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldPancakes, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxIceCream, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFormattedTextFieldIceCream, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxMuffin)
                    .addComponent(jFormattedTextFieldMuffin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxPancakes)
                    .addComponent(jFormattedTextFieldPancakes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldSoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxSoda))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 61, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxCoffee)
                            .addComponent(jFormattedTextFieldCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxTea)
                            .addComponent(jFormattedTextFieldTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 280, 420));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 4));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 180, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFieldIceCreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldIceCreamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldIceCreamActionPerformed

    private void jFormattedTextFieldFriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldFriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldFriesActionPerformed

    private void jCheckBoxIceCreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxIceCreamActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxIceCream.isSelected()){
            jFormattedTextFieldIceCream.setEnabled(true);
        }
        else{
             jFormattedTextFieldIceCream.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxIceCreamActionPerformed

    private void jCheckBoxPancakesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPancakesActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxPancakes.isSelected()){
            jFormattedTextFieldPancakes.setEnabled(true);
        }
        else{
             jFormattedTextFieldPancakes.setEnabled(false);
        }
        
    }//GEN-LAST:event_jCheckBoxPancakesActionPerformed

    private void jCheckBoxFriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFriesActionPerformed
        // TODO add your handling code here:
         if(jCheckBoxFries.isSelected()){
            jFormattedTextFieldFries.setEnabled(true);
        }
        else{
             jFormattedTextFieldFries.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxFriesActionPerformed

    private void jFormattedTextFieldChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldChickenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldChickenActionPerformed

    private void jFormattedTextFieldSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldSandwichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldSandwichActionPerformed

    private void jFormattedTextFieldSoupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldSoupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldSoupActionPerformed

    private void jFormattedTextFieldOnionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldOnionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldOnionActionPerformed

    private void jFormattedTextFieldPancakesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPancakesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldPancakesActionPerformed

    private void jFormattedTextFieldMuffinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldMuffinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldMuffinActionPerformed

    private void jFormattedTextFieldBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldBurgerActionPerformed

    private void jCheckBoxTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTeaActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxTea.isSelected()){
            jFormattedTextFieldTea.setEnabled(true);
        }
        else{
             jFormattedTextFieldTea.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxTeaActionPerformed

    private void jCheckBoxSodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSodaActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxSoda.isSelected()){
            jFormattedTextFieldSoda.setEnabled(true);
        }
        else{
             jFormattedTextFieldSoda.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxSodaActionPerformed

    private void jFormattedTextFieldSodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldSodaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldSodaActionPerformed

    private void jFormattedTextFieldCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCoffeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCoffeeActionPerformed

    private void jFormattedTextFieldTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTeaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldTeaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBoxBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBurgerActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxBurger.isSelected()){
            jFormattedTextFieldBurger.setEnabled(true);
        }
        else{
             jFormattedTextFieldBurger.setEnabled(false);
        }
            
    }//GEN-LAST:event_jCheckBoxBurgerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jFormattedTextFieldSalad.setText(null);
        jFormattedTextFieldFries.setText(null);
        jFormattedTextFieldChicken.setText(null);
        jFormattedTextFieldSandwich.setText(null);
        jFormattedTextFieldSoup.setText(null);
        jFormattedTextFieldOnion.setText(null);
        jFormattedTextFieldBurger.setText(null);
       
        jFormattedTextFieldIceCream.setText(null);
        jFormattedTextFieldPancakes.setText(null);
        jFormattedTextFieldMuffin.setText(null);
      
        
        
        jFormattedTextFieldSoda.setText(null);
        jFormattedTextFieldCoffee.setText(null);
        jFormattedTextFieldTea.setText(null);
        
        
        jCheckBoxFries.setSelected(false);
        jCheckBoxBurger.setSelected(false);
        jCheckBoxChicken.setSelected(false);
        jCheckBoxSalad.setSelected(false);
        jCheckBoxSandwich.setSelected(false);
        jCheckBoxOnion.setSelected(false);
        jCheckBoxSoup.setSelected(false);
        
        jCheckBoxIceCream.setSelected(false);
        jCheckBoxPancakes.setSelected(false);
        jCheckBoxMuffin.setSelected(false);
        
        jCheckBoxTea.setSelected(false);
        jCheckBoxCoffee.setSelected(false);
        jCheckBoxSoda.setSelected(false);
        
        jFormattedTextFieldBurger.setEnabled(false);
        jFormattedTextFieldFries.setEnabled(false);
        jFormattedTextFieldSalad.setEnabled(false);
        jFormattedTextFieldSandwich.setEnabled(false);
        jFormattedTextFieldChicken.setEnabled(false);
        jFormattedTextFieldOnion.setEnabled(false);
        jFormattedTextFieldSoup.setEnabled(false);
         jFormattedTextFieldIceCream.setEnabled(false);
         jFormattedTextFieldPancakes.setEnabled(false);
         jFormattedTextFieldMuffin.setEnabled(false);
         jFormattedTextFieldTea.setEnabled(false);
        jFormattedTextFieldCoffee.setEnabled(false);
        jFormattedTextFieldSoda.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jFormattedTextFieldBurgerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldBurgerKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber==KeyEvent.VK_BACK_SPACE)
                ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jFormattedTextFieldBurgerKeyTyped

    private void jFormattedTextFieldFriesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldFriesKeyTyped
            // TODO add your handling code here:
            char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber==KeyEvent.VK_BACK_SPACE)
                ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jFormattedTextFieldFriesKeyTyped

    private void jCheckBoxSaladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSaladActionPerformed
        // TODO add your handling code here:
         if(jCheckBoxSalad.isSelected()){
            jFormattedTextFieldSalad.setEnabled(true);
        }
        else{
             jFormattedTextFieldSalad.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxSaladActionPerformed

    private void jFormattedTextFieldSaladKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldSaladKeyTyped
        // TODO add your handling code here:
         char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber==KeyEvent.VK_BACK_SPACE)
                ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jFormattedTextFieldSaladKeyTyped

    private void jCheckBoxChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxChickenActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxChicken.isSelected()){
            jFormattedTextFieldChicken.setEnabled(true);
        }
        else{
             jFormattedTextFieldChicken.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxChickenActionPerformed

    private void jCheckBoxSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSandwichActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxSandwich.isSelected()){
            jFormattedTextFieldSandwich.setEnabled(true);
        }
        else{
             jFormattedTextFieldSandwich.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxSandwichActionPerformed

    private void jCheckBoxOnionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxOnionActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxOnion.isSelected()){
            jFormattedTextFieldOnion.setEnabled(true);
        }
        else{
             jFormattedTextFieldOnion.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxOnionActionPerformed

    private void jCheckBoxSoupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSoupActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxSoup.isSelected()){
            jFormattedTextFieldSoup.setEnabled(true);
        }
        else{
             jFormattedTextFieldSoup.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxSoupActionPerformed

    private void jCheckBoxMuffinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMuffinActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxMuffin.isSelected()){
            jFormattedTextFieldMuffin.setEnabled(true);
        }
        else{
             jFormattedTextFieldMuffin.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxMuffinActionPerformed

    private void jCheckBoxCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCoffeeActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxCoffee.isSelected()){
            jFormattedTextFieldCoffee.setEnabled(true);
        }
        else{
             jFormattedTextFieldCoffee.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxCoffeeActionPerformed

    private void jFormattedTextFieldChickenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldChickenKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber==KeyEvent.VK_BACK_SPACE)
                ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jFormattedTextFieldChickenKeyTyped

    private void jFormattedTextFieldSandwichKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldSandwichKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber==KeyEvent.VK_BACK_SPACE)
                ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jFormattedTextFieldSandwichKeyTyped

    private void jFormattedTextFieldOnionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldOnionKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber==KeyEvent.VK_BACK_SPACE)
                ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jFormattedTextFieldOnionKeyTyped

    private void jFormattedTextFieldSoupKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldSoupKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber==KeyEvent.VK_BACK_SPACE)
                ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jFormattedTextFieldSoupKeyTyped

    private void jFormattedTextFieldIceCreamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldIceCreamKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber==KeyEvent.VK_BACK_SPACE)
                ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jFormattedTextFieldIceCreamKeyTyped

    private void jFormattedTextFieldMuffinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldMuffinKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber==KeyEvent.VK_BACK_SPACE)
                ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jFormattedTextFieldMuffinKeyTyped

    private void jFormattedTextFieldPancakesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPancakesKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber==KeyEvent.VK_BACK_SPACE)
                ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jFormattedTextFieldPancakesKeyTyped

    private void jFormattedTextFieldSodaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldSodaKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber==KeyEvent.VK_BACK_SPACE)
                ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jFormattedTextFieldSodaKeyTyped

    private void jFormattedTextFieldCoffeeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCoffeeKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber==KeyEvent.VK_BACK_SPACE)
                ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jFormattedTextFieldCoffeeKeyTyped

    private void jFormattedTextFieldTeaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTeaKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber==KeyEvent.VK_BACK_SPACE)
                ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jFormattedTextFieldTeaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Food().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBoxBurger;
    private javax.swing.JCheckBox jCheckBoxChicken;
    private javax.swing.JCheckBox jCheckBoxCoffee;
    private javax.swing.JCheckBox jCheckBoxFries;
    private javax.swing.JCheckBox jCheckBoxIceCream;
    private javax.swing.JCheckBox jCheckBoxMuffin;
    private javax.swing.JCheckBox jCheckBoxOnion;
    private javax.swing.JCheckBox jCheckBoxPancakes;
    private javax.swing.JCheckBox jCheckBoxSalad;
    private javax.swing.JCheckBox jCheckBoxSandwich;
    private javax.swing.JCheckBox jCheckBoxSoda;
    private javax.swing.JCheckBox jCheckBoxSoup;
    private javax.swing.JCheckBox jCheckBoxTea;
    private javax.swing.JFormattedTextField jFormattedTextFieldBurger;
    private javax.swing.JFormattedTextField jFormattedTextFieldChicken;
    private javax.swing.JFormattedTextField jFormattedTextFieldCoffee;
    private javax.swing.JFormattedTextField jFormattedTextFieldFries;
    private javax.swing.JFormattedTextField jFormattedTextFieldIceCream;
    private javax.swing.JFormattedTextField jFormattedTextFieldMuffin;
    private javax.swing.JFormattedTextField jFormattedTextFieldOnion;
    private javax.swing.JFormattedTextField jFormattedTextFieldPancakes;
    private javax.swing.JFormattedTextField jFormattedTextFieldSalad;
    private javax.swing.JFormattedTextField jFormattedTextFieldSandwich;
    private javax.swing.JFormattedTextField jFormattedTextFieldSoda;
    private javax.swing.JFormattedTextField jFormattedTextFieldSoup;
    private javax.swing.JFormattedTextField jFormattedTextFieldTea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
